openapi: 3.0.1
info:
  title: anblog
  description: It's a *very* simple blog API. Code is [here](https://github.com/ankeesler/anblog).
  version: 1.0.0
servers:
- url: https://anblog.cfapps.io
  description: Primary anblog service
- url: https://localhost:9090
  description: Development anblog service
tags:
- name: post
  description: A blog post
paths:
  /posts:
    get:
      tags:
      - post
      summary: Get all posts
      operationId: getAllPosts
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
      security:
      - petstore_auth:
        - read:posts
    post:
      tags:
        - post
      summary: Add a new post
      operationId: addPost
      requestBody:
        description: Post object to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        405:
          description: Invalid input
          content: {}
      security:
        - petstore_auth:
            - write:posts
            - read:posts
  /posts/{postPath}:
    get:
      tags:
      - post
      summary: Get post by path
      description: Returns a single post
      operationId: getPostByPath
      parameters:
      - name: postPath
        in: path
        description: The path of the post to return
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        404:
          description: Post not found
          content: {}
      security:
      - petstore_auth:
        - read:posts
    put:
      tags:
      - post
      summary: Update an existing post
      operationId: updatePost
      requestBody:
        description: Post object to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
        required: true
      parameters:
      - name: postPath
        in: path
        description: The path of the post to return
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        400:
          description: Invalid path supplied
          content: {}
        404:
          description: Post not found
          content: {}
        405:
          description: Validation exception
          content: {}
      security:
      - blog_auth:
        - write:posts
        - read:posts
    delete:
      tags:
      - post
      summary: Deletes a post
      operationId: deletePost
      parameters:
      - name: postPath
        in: path
        description: The path of the post to delete
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        400:
          description: Invalid path supplied
          content: {}
        404:
          description: Post not found
          content: {}
      security:
      - blob_auth:
        - write:pets
        - read:pets
components:
  schemas:
    Post:
      type: object
      properties:
        path:
          type: string
          maxLength: 100
          pattern: '^(\.[a-z0-9]+)+$'
        content:
          type: string
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
  securitySchemes:
    blog_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/oauth/dialog
          scopes:
            write:posts: modify posts in your account
            read:posts: read posts in your account
