openapi: 3.0.1
info:
  title: anblog
  description: It's a *very* simple blog API. Code is [here](https://github.com/ankeesler/anblog).
  version: 1.0.0
servers:
- url: https://anblog.cfapps.io
  description: Primary anblog service
- url: https://localhost:9090
  description: Development anblog service
tags:
- name: post
  description: A blog post
paths:
  /posts:
    get:
      tags:
      - post
      summary: Get all posts in ascending alphanumeric order of path
      operationId: getAllPosts
      parameters:
      - name: prefix
        in: query
        description: A path prefix used to filter returned posts
        required: false
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
      security:
      - blog_auth: []
    post:
      tags:
        - post
      summary: Add a new post
      operationId: addPost
      requestBody:
        description: Post object to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        405:
          description: Invalid input
          content: {}
      security:
      - blog_auth: []
  /posts/{postPath}:
    get:
      tags:
      - post
      summary: Get post by path
      description: Returns a single post
      operationId: getPostByPath
      parameters:
      - name: postPath
        in: path
        description: The path of the post to return
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        404:
          description: Post not found
          content: {}
      security:
      - blog_auth: []
    put:
      tags:
      - post
      summary: Update an existing post
      operationId: updatePost
      requestBody:
        description: Post object to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
        required: true
      parameters:
      - name: postPath
        in: path
        description: The path of the post to return
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        400:
          description: Invalid path supplied
          content: {}
        404:
          description: Post not found
          content: {}
        405:
          description: Validation exception
          content: {}
      security:
      - blog_auth: []
    delete:
      tags:
      - post
      summary: Deletes a post
      operationId: deletePost
      parameters:
      - name: postPath
        in: path
        description: The path of the post to delete
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        400:
          description: Invalid path supplied
          content: {}
        404:
          description: Post not found
          content: {}
      security:
      - blog_auth: []
components:
  schemas:
    Post:
      type: object
      required:
      - path
      - content
      - created
      - modified
      properties:
        path:
          description: Unique path
          type: string
          maxLength: 100
          pattern: '^(\.[a-z0-9]+)+$'
        content:
          description: Actual text of blog post
          type: string
        created:
          description: Seconds since 1970
          type: integer
          format: int64
        modified:
          description: Seconds since 1970
          type: integer
          format: int64
  securitySchemes:
    blog_auth:
      type: http
      scheme: basic