=begin
#anblog

#It's a *very* simple blog API. Code is [here](https://github.com/ankeesler/anblog).

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

module Anblog
  VERSION = '1.0.0'
end
