=begin
#anblog

#Its a *very* simple blog API. Code is [here](https://github.com/ankeesler/anblog).

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Anblog::PostApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PostApi' do
  before do
    # run before each test
    @api_instance = Anblog::PostApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PostApi' do
    it 'should create an instance of PostApi' do
      expect(@api_instance).to be_instance_of(Anblog::PostApi)
    end
  end

  # unit tests for add_post
  # Add a new post
  # @param post Post object to add
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_post
  # Deletes a post
  # @param post_id Post id to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_posts
  # Get all posts
  # @param [Hash] opts the optional parameters
  # @return [Array<Post>]
  describe 'get_all_posts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_post_by_id
  # Get post by ID
  # Returns a single post
  # @param post_id ID of post to return
  # @param [Hash] opts the optional parameters
  # @return [Post]
  describe 'get_post_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_post
  # Update an existing post
  # @param post_id ID of post to return
  # @param post Post object to update
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
