=begin
#anblog

#It's a *very* simple blog API. Code is [here](https://github.com/ankeesler/anblog).

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

# Common files
require 'anblog/api_client'
require 'anblog/api_error'
require 'anblog/version'
require 'anblog/configuration'
require 'anblog/opener'
require 'anblog/editor'
require 'anblog/timer'

# Models
require 'anblog/models/post'

# APIs
require 'anblog/api/post_api'

module Anblog
  class << self
    # Customize default settings for the SDK using block.
    #   Anblog.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
